settings:
  title: 'Saobby 状态 (CF Worker监测点)'
  url: 'https://status.saobby.tk' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统运行正常'
  notAllmonitorsOperational: '部分系统故障'
  monitorLabelOperational: '运行正常'
  monitorLabelNotOperational: '故障'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 次故障' # xx incident(s) recorded

monitors:
  - id: saobby-home # unique identifier
    name: 'Saobby 个人主页前端'
    description: 'Saobby 的个人主页的前端' # default=empty
    url: 'https://www.saobby.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: saobby-pythonanywhere
    name: 'Saobby Pythonanywhere 主页'
    description: 'Saobby 的 Pythonanywhere 主页'
    url: 'https://saobby.pythonanywhere.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: github-proxy
    name: 'Github 反向代理'
    description: 'Github 反向代理'
    url: 'https://github.gitblock.cf/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: scratch-proxy
    name: 'Scratch 官网反向代理'
    description: 'Scratch 官网反向代理'
    url: 'https://scratch.gitblock.cf/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: aerfaying-isolator-query
    name: '阿儿法营路障查询机'
    description: '阿儿法营路障查询机'
    url: 'https://isolator.saobby.tk/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: api-v2
    name: '新版 API 服务'
    description: '新版 API 服务，部署在一台香港服务器'
    url: 'https://aether.saobby.com:9999/api/check_alive'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: captcha-v2
    name: 'SaobbyCaptchaV2'
    description: 'Saobby 的第二版人机验证'
    url: 'https://aether.saobby.com:5001/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false